language: node_js
dist: focal
node_js:
- '20.18.3'
env:
  global:
  - MATTERMOST_CHANNEL=publication
  - secure: BgLoSPUecHA7qWjSp7qFLaPkl/o5hJmihffsXh8FveogYtbFRKOZoY+0mwCBcYBeuO3oAieObHF0ZZ0inMD1DPezC5wWlMku85zp7oUW0XfJn++o+AaG1yCRaQN9s4XTR5Y5nBVBEsFe3QQr+6vdPuHY4V/JQT+auAPjs7rBVJ78RFO3munKi6sEA2UMo7ztKB/OySqHLF+BDJTRpA9pJFlI5MI4FGt5971xEM0qj6wFKSj0s/3r+S80i34Wy/XxI0EGCBmz+XQTZexA5oFE/JqePw88PTYOTCb/eTHL1aS7CM6Ue/9VIDneYmP16tDVABSdYy70o9ttb59D0CL5pSBiNtF4ZDptrKy55f5joVaHIeoQdEcFOsiNc0XU40FzxGbUM0NPTFlo68se/XqcxwWLq3/9nPTwLSFnxEKurRHKtS76P6stfaKVyejwvHYol4AZkT6TalD1ai3uRnagGRvUruxAGlwWvfJ1uGbJAEpiYbj+Wako5i6tuDnpp0R829GraX/9yZJkrCA1PjslTO2AwYzFdnRbbxao5QEZ7aPbjd2tRjWiTXovBpjgokR0qjn9Et18Jj7qztg2C+SEvYtITFqztBjr2DvDG4WlsRCWbHHIj+DJLYZuRLUre/cMDbDc/z2ixl881KvI6euotFVC+5T4kSatcHO9lAhgjw0=
  # MATTERMOST_HOOK_URL
  - secure: ehNTj2kwGECCMPDtlGmCz7Mn2krRPCoQx0wtGCX8bW2tLhvXWPTCjgprXc2jYdJc6Oejx45UfRNc+i+hXGYj1yaibcZYOwtAHBWI7QKs6j5myDhpFrBgbPOKNmynGpK5trw20Tb6qL/lwV8UsgSGzVupplC8xh4oHtJnQ8xXKCyYbIKU1DXoegDzOVhnVeKwihcO3MolYVMZnOV/JdU7T5TYhgP8cukMBJk4iQ+UPBiRU5tj8vT3ujXJSiDabGw+tZqoWSRvARsYJm7XzdCkwTcD5HqpLZkFNvMYSYpFiu58pTLOH5HH9mX8AcvhSNY/AEZS3Vfed6L6HW0F34q6GMk6FhVSt3jnBs94SYJC34QzLiA+H1Vy8sd+xZ1OobJQbtdwNISCvVFxABd1uEsQd0BFp+6/uThgskgAnVq7T8IkkBhtfja9KAyn7pNg1cvtI1UZ/Isd+7Orkn9C5ltDqv9TEasErynXtc3VuD5r1QPSA7iA4zzu6J/qPUT/zvkPw8Eort6red4Kv83HOIgjRdihTNue0MyiU931dACfiBkhfN2nF7yHt4wu73w/eSWjHOzeSpCEWpj9VX//5puC+fcpGUV+DPCcrAbEYkqLrPrK70+FNzxiNEoToTQFjSvnSbVdx7UrFZYG0RMDSM48zIQjSxyk3Uk2up4+aBFeMVw=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - build-debug
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    branch:
    - master
    - main
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish --postpublish mattermost
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_8ebb1ef83f64_key -iv $encrypted_8ebb1ef83f64_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- if [[ -f /tmp/github_deploy_key ]]; then chmod 600 /tmp/github_deploy_key; fi
- if [[ -f /tmp/github_deploy_key ]]; then ssh-add /tmp/github_deploy_key; fi
after_deploy:
- rm -f /tmp/github_deploy_key
- ssh-add -D
